module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['.'],
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
        ],
        alias: {
          '@navigators': './src/navigators',
          '@screens': './src/screens',
          '@widgets': './src/widgets',
          '@features': './src/features',
          '@entities': './src/entities',
          '@utils': './src/shared/utils',
          '@stores': './src/shared/stores',
          '@hooks': './src/shared/hooks',
          '@typings': './src/shared/typings',
          '@consts': './src/shared/consts',
          '@components': './src/shared/components',
          '@styles': './src/shared/styles',
          '@theme': './src/shared/theme.ts',
          '@contracts': './src/shared/contracts/index.ts',
          '@locale': './src/shared/locales/index.ts',
          '@config': './config/config.json',
          '@package': './package.json',
          '@assets': './assets',
          '@src': './src',
        },
      },
    ],
    // 'hot-updater/babel-plugin',
    // 'react-native-worklets/plugin',
  ],
};
